linters:
  presets:
  - bugs
  - complexity
  - unused
  - performance
  - format
  - style
  disable:
  - nlreturn
  - goerr113
  - gochecknoglobals
  - exhaustivestruct
  - bodyclose
  - wsl
  - maligned
  - funlen
  - dupl
linters-settings:
  maligned: {suggest-new: true}
  lll: {line-length: 120}