name: test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with: {go-version: '1.15'}
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with: {version: 'v1.32'}
      - name: Test
        env:
          GOODREADS_KEY: '${{ secrets.GOODREADS_KEY }}'
          SKIP_LINT: 'true'
        run: make test